//
// Created by noah on 08.07.20.
//

#ifndef DYNAMICBINARYTRANSLATORRISCV64_X86_64_ANALYZE_H
#define DYNAMICBINARYTRANSLATORRISCV64_X86_64_ANALYZE_H

void analyze(const char *file_path);
#endif //DYNAMICBINARYTRANSLATORRISCV64_X86_64_ANALYZE_H
