//
// Created by noah on 12.07.20.
//

#include "typedefs.h"

char* errorcode_to_string(int errorcode){
    switch (errorcode) {
        case E_UNKNOWN:
            return "unknown";
        case E_f3_32:
            return "unknown funct3 code for OP_32";
        case E_f3_AMO:
            return "unknown funct3 code for OP_AMO";
        case E_f3_BRANCH:
            return "unknown funct3 code for OP_BRANCH";
        case E_f3_IMM:
            return "unknown funct3 code for OP_IMM";
        case E_f3_IMM_32:
            return "unknown funct3 code for OP_IMM_32";
        case E_f3_LOAD:
            return "unknown funct3 code for OP_LOAD";
        case E_f3_STORE:
            return "unknown funct3 code for OP_STORE";
        case E_f3_MISC_MEM:
            return "unknown funct3 code for OP_MISC_MEM";
        case E_f3_RV64M:
            return "unknown funct3 code for RV64M";
        case E_f3_SYSTEM:
            return "unknown funct3 code for OP_SYSTEM";
        case E_f3_OP:
            return "unknown funct3 code for OP_OP";
        case E_f7_AMO:
            return "unknown funct7 code for OP_AMO";
        default:
            return "unknown error code";
    }
}

char *mnem_to_string(int mnem) {
    switch (mnem) {
        case LUI:
            return "LUI";
        case AUIPC:
            return "AUIPC";
        case JAL:
            return "JAL";
        case JALR:
            return "JALR";
        case BEQ:
            return "BEQ";
        case BNE:
            return "BNE";
        case BLT:
            return "BLT";
        case BGE:
            return "BGE";
        case BLTU:
            return "BLTU";
        case BGEU:
            return "BGEU";
        case LB:
            return "LB";
        case LH:
            return "LH";
        case LW:
            return "LW";
        case LBU:
            return "LBU";
        case LHU:
            return "LHU";
        case SB:
            return "SB";
        case SH:
            return "SH";
        case SW:
            return "SW";
        case ADDI:
            return "ADDI";
        case SLTI:
            return "SLTI";
        case SLTIU:
            return "SLTIU";
        case XORI:
            return "XORI";
        case ORI:
            return "ORI";
        case ANDI:
            return "ANDI";
        case SLLI:
            return "SLLI";
        case SRLI:
            return "SRLI";
        case SRAI:
            return "SRAI";
        case ADD:
            return "ADD";
        case SUB:
            return "SUB";
        case SLL:
            return "SLL";
        case SLT:
            return "SLT";
        case SLTU:
            return "SLTU";
        case XOR:
            return "XOR";
        case SRL:
            return "SRL";
        case SRA:
            return "SRA";
        case OR:
            return "OR";
        case AND:
            return "AND";
        case FENCE:
            return "FENCE";
        case ECALL:
            return "ECALL";
        case EBREAK:
            return "EBREAK";
        case FENCE_I:
            return "FENCE_I";
        case CSRRW:
            return "CSRRW";
        case CSRRS:
            return "CSRRS";
        case CSRRC:
            return "CSRRC";
        case CSRRWI:
            return "CSRRWI";
        case CSRRSI:
            return "CSRRSI";
        case CSRRCI:
            return "CSRRCI";
        case LWU:
            return "LWU";
        case LD:
            return "LD";
        case SD:
            return "SD";
        case ADDIW:
            return "ADDIW";
        case SLLIW:
            return "SLLIW";
        case SRLIW:
            return "SRLIW";
        case SRAIW:
            return "SRAIW";
        case ADDW:
            return "ADDW";
        case SUBW:
            return "SUBW";
        case SLLW:
            return "SLLW";
        case SRLW:
            return "SRLW";
        case SRAW:
            return "SRAW";
        case MUL:
            return "MUL";
        case MULH:
            return "MULH";
        case MULHSU:
            return "MULHSU";
        case MULHU:
            return "MULHU";
        case DIV:
            return "DIV";
        case DIVU:
            return "DIVU";
        case REM:
            return "REM";
        case REMU:
            return "REMU";
        case MULW:
            return "MULW";
        case DIVW:
            return "DIVW";
        case DIVUW:
            return "DIVUW";
        case REMW:
            return "REMW";
        case REMUW:
            return "REMUW";
        case LRW:
            return "LRW";
        case SCW:
            return "SCW";
        case AMOSWAPW:
            return "AMOSWAPW";
        case AMOADDW:
            return "AMOADDW";
        case AMOXORW:
            return "AMOXORW";
        case AMOANDW:
            return "AMOANDW";
        case AMOORW:
            return "AMOORW";
        case AMOMINW:
            return "AMOMINW";
        case AMOMAXW:
            return "AMOMAXW";
        case AMOMINUW:
            return "AMOMINUW";
        case AMOMAXUW:
            return "AMOMAXUW";
        case LRD:
            return "LRD";
        case SCD:
            return "SCD";
        case AMOSWAPD:
            return "AMOSWAPD";
        case AMOADDD:
            return "AMOADDD";
        case AMOXORD:
            return "AMOXORD";
        case AMOANDD:
            return "AMOANDD";
        case AMOORD:
            return "AMOORD";
        case AMOMIND:
            return "AMOMIND";
        case AMOMAXD:
            return "AMOMAXD";
        case AMOMINUD:
            return "AMOMINUD";
        case AMOMAXUD:
            return "AMOMAXUD";
        case FLW:
            return "FLW";
        case FSW:
            return "FSW";
        case FMADDS:
            return "FMADDS";
        case FMSUBS:
            return "FMSUBS";
        case FNMSUBS:
            return "FNMSUBS";
        case FNMADDS:
            return "FNMADDS";
        case FADDS:
            return "FADDS";
        case FSUBS:
            return "FSUBS";
        case FMULS:
            return "FMULS";
        case FDIVS:
            return "FDIVS";
        case FSQRTS:
            return "FSQRTS";
        case FSGNJS:
            return "FSGNJS";
        case FSGNJNS:
            return "FSGNJNS";
        case FSGNJXS:
            return "FSGNJXS";
        case FMINS:
            return "FMINS";
        case FMAXS:
            return "FMAXS";
        case FCVTWS:
            return "FCVTWS";
        case FCVTWUS:
            return "FCVTWUS";
        case FMVXW:
            return "FMVXW";
        case FEQS:
            return "FEQS";
        case FLTS:
            return "FLTS";
        case FLES:
            return "FLES";
        case FCLASSS:
            return "FCLASSS";
        case FCVTSW:
            return "FCVTSW";
        case FCVTSWU:
            return "FCVTSWU";
        case FMVWX:
            return "FMVWX";
        case FCVTLS:
            return "FCVTLS";
        case FCVTLUS:
            return "FCVTLUS";
        case FCVTSL:
            return "FCVTSL";
        case FCVTSLU:
            return "FCVTSLU";
        case FLD:
            return "FLD";
        case FSD:
            return "FSD";
        case FMADDD:
            return "FMADDD";
        case FMSUBD:
            return "FMSUBD";
        case FNMSUBD:
            return "FNMSUBD";
        case FNMADDD:
            return "FNMADDD";
        case FADDD:
            return "FADDD";
        case FSUBD:
            return "FSUBD";
        case FMULD:
            return "FMULD";
        case FDIVD:
            return "FDIVD";
        case FSQRTD:
            return "FSQRTD";
        case FSGNJD:
            return "FSGNJD";
        case FSGNJND:
            return "FSGNJND";
        case FSGNJXD:
            return "FSGNJXD";
        case FMIND:
            return "FMIND";
        case FMAXD:
            return "FMAXD";
        case FCVTSD:
            return "FCVTSD";
        case FCVTDS:
            return "FCVTDS";
        case FEQD:
            return "FEQD";
        case FLTD:
            return "FLTD";
        case FLED:
            return "FLED";
        case FCLASSD:
            return "FCLASSD";
        case FCVTWD:
            return "FCVTWD";
        case FCVTWUD:
            return "FCVTWUD";
        case FCVTDW:
            return "FCVTDW";
        case FCVTDWU:
            return "FCVTDWU";
        case FCVTLD:
            return "FCVTLD";
        case FCVTLUD:
            return "FCVTLUD";
        case FMVXD:
            return "FMVXD";
        case FCVTDL:
            return "FCVTDL";
        case FCVTDLU:
            return "FCVTDLU";
        case FMVDX:
            return "FMVDX";
        case NOP:
            return "NOP";
        case SILENT_NOP:
            return "SILENT_NOP";
        case MV:
            return "MV";
        case NOT:
            return "NOT";
        case NEG:
            return "NEG";
        case NEGW:
            return "NEGW";
        case SEXTW:
            return "SEXTW";
        case SEQZ:
            return "SEQZ";
        case SNEZ:
            return "SNEZ";
        case SLTZ:
            return "SLTZ";
        case SGTZ:
            return "SGTZ";
        case LI:
            return "LI";
        default:
            return "UNKNOWN";
    }
}

char *reg_to_string(int reg) {
    switch (reg) {
        case x0:
            return "x0";
        case x1:
            return "x1";
        case x2:
            return "x2";
        case x3:
            return "x3";
        case x4:
            return "x4";
        case x5:
            return "x5";
        case x6:
            return "x6";
        case x7:
            return "x7";
        case x8:
            return "x8";
        case x9:
            return "x9";
        case x10:
            return "x10";
        case x11:
            return "x11";
        case x12:
            return "x12";
        case x13:
            return "x13";
        case x14:
            return "x14";
        case x15:
            return "x15";
        case x16:
            return "x16";
        case x17:
            return "x17";
        case x18:
            return "x18";
        case x19:
            return "x19";
        case x20:
            return "x20";
        case x21:
            return "x21";
        case x22:
            return "x22";
        case x23:
            return "x23";
        case x24:
            return "x24";
        case x25:
            return "x25";
        case x26:
            return "x26";
        case x27:
            return "x27";
        case x28:
            return "x28";
        case x29:
            return "x29";
        case x30:
            return "x30";
        case x31:
            return "x31";
        default:
            return "INVALID";
    }
}

char *reg_to_alias(int reg) {
    switch (reg) {
        case zero:
            return "zero";
        case ra:
            return "ra";
        case sp:
            return "sp";
        case gp:
            return "gp";
        case tp:
            return "tp";
        case t0:
            return "t0";
        case t1:
            return "t1";
        case t2:
            return "t2";
        case s0:
            return "s0/fp";
        case s1:
            return "s1";
        case a0:
            return "a0";
        case a1:
            return "a1";
        case a2:
            return "a2";
        case a3:
            return "a3";
        case a4:
            return "a4";
        case a5:
            return "a5";
        case a6:
            return "a6";
        case a7:
            return "a7";
        case s2:
            return "s2";
        case s3:
            return "s3";
        case s4:
            return "s4";
        case s5:
            return "s5";
        case s6:
            return "s6";
        case s7:
            return "s7";
        case s8:
            return "s8";
        case s9:
            return "s9";
        case s10:
            return "s10";
        case s11:
            return "s11";
        case t3:
            return "t3";
        case t4:
            return "t4";
        case t5:
            return "t5";
        case t6:
            return "t6";
        default:
            return "INVALID";
    }
}
