//
// Created by noah on 12.07.20.
//

#include "typedefs.h"


char *mnem_to_string(int mnem) {
    switch (mnem) {
        case LUI:
            return "LUI";
        case AUIPC:
            return "AUIPC";
        case JAL:
            return "JAL";
        case JALR:
            return "JALR";
        case BEQ:
            return "BEQ";
        case BNE:
            return "BNE";
        case BLT:
            return "BLT";
        case BGE:
            return "BGE";
        case BLTU:
            return "BLTU";
        case BGEU:
            return "BGEU";
        case LB:
            return "LB";
        case LH:
            return "LH";
        case LW:
            return "LW";
        case LBU:
            return "LBU";
        case LHU:
            return "LHU";
        case SB:
            return "SB";
        case SH:
            return "SH";
        case SW:
            return "SW";
        case ADDI:
            return "ADDI";
        case SLTI:
            return "SLTI";
        case SLTIU:
            return "SLTIU";
        case XORI:
            return "XORI";
        case ORI:
            return "ORI";
        case ANDI:
            return "ANDI";
        case SLLI:
            return "SLLI";
        case SRLI:
            return "SRLI";
        case SRAI:
            return "SRAI";
        case ADD:
            return "ADD";
        case SUB:
            return "SUB";
        case SLL:
            return "SLL";
        case SLT:
            return "SLT";
        case SLTU:
            return "SLTU";
        case XOR:
            return "XOR";
        case SRL:
            return "SRL";
        case SRA:
            return "SRA";
        case OR:
            return "OR";
        case AND:
            return "AND";
        case FENCE:
            return "FENCE";
        case ECALL:
            return "ECALL";
        case EBREAK:
            return "EBREAK";
        case FENCE_I:
            return "FENCE_I";
        case CSRRW:
            return "CSRRW";
        case CSRRS:
            return "CSRRS";
        case CSRRC:
            return "CSRRC";
        case CSRRWI:
            return "CSRRWI";
        case CSRRSI:
            return "CSRRSI";
        case CSRRCI:
            return "CSRRCI";
        case LWU:
            return "LWU";
        case LD:
            return "LD";
        case SD:
            return "SD";
        case ADDIW:
            return "ADDIW";
        case SLLIW:
            return "SLLIW";
        case SRLIW:
            return "SRLIW";
        case SRAIW:
            return "SRAIW";
        case ADDW:
            return "ADDW";
        case SUBW:
            return "SUBW";
        case SLLW:
            return "SLLW";
        case SRLW:
            return "SRLW";
        case SRAW:
            return "SRAW";
        case MUL:
            return "MUL";
        case MULH:
            return "MULH";
        case MULHSU:
            return "MULHSU";
        case MULHU:
            return "MULHU";
        case DIV:
            return "DIV";
        case DIVU:
            return "DIVU";
        case REM:
            return "REM";
        case REMU:
            return "REMU";
        case MULW:
            return "MULW";
        case DIVW:
            return "DIVW";
        case DIVUW:
            return "DIVUW";
        case REMW:
            return "REMW";
        case REMUW:
            return "REMUW";
        case LRW:
            return "LRW";
        case SCW:
            return "SCW";
        case AMOSWAPW:
            return "AMOSWAPW";
        case AMOADDW:
            return "AMOADDW";
        case AMOXORW:
            return "AMOXORW";
        case AMOANDW:
            return "AMOANDW";
        case AMOORW:
            return "AMOORW";
        case AMOMINW:
            return "AMOMINW";
        case AMOMAXW:
            return "AMOMAXW";
        case AMOMINUW:
            return "AMOMINUW";
        case AMOMAXUW:
            return "AMOMAXUW";
        case LRD:
            return "LRD";
        case SCD:
            return "SCD";
        case AMOSWAPD:
            return "AMOSWAPD";
        case AMOADDD:
            return "AMOADDD";
        case AMOXORD:
            return "AMOXORD";
        case AMOANDD:
            return "AMOANDD";
        case AMOORD:
            return "AMOORD";
        case AMOMIND:
            return "AMOMIND";
        case AMOMAXD:
            return "AMOMAXD";
        case AMOMINUD:
            return "AMOMINUD";
        case AMOMAXUD:
            return "AMOMAXUD";
        case FLW:
            return "FLW";
        case FSW:
            return "FSW";
        case FMADDS:
            return "FMADDS";
        case FMSUBS:
            return "FMSUBS";
        case FNMSUBS:
            return "FNMSUBS";
        case FNMADDS:
            return "FNMADDS";
        case FADDS:
            return "FADDS";
        case FSUBS:
            return "FSUBS";
        case FMULS:
            return "FMULS";
        case FDIVS:
            return "FDIVS";
        case FSQRTS:
            return "FSQRTS";
        case FSGNJS:
            return "FSGNJS";
        case FSGNJNS:
            return "FSGNJNS";
        case FSGNJXS:
            return "FSGNJXS";
        case FMINS:
            return "FMINS";
        case FMAXS:
            return "FMAXS";
        case FCVTWS:
            return "FCVTWS";
        case FCVTWUS:
            return "FCVTWUS";
        case FMVXW:
            return "FMVXW";
        case FEQS:
            return "FEQS";
        case FLTS:
            return "FLTS";
        case FLES:
            return "FLES";
        case FCLASSS:
            return "FCLASSS";
        case FCVTSW:
            return "FCVTSW";
        case FCVTSWU:
            return "FCVTSWU";
        case FMVWX:
            return "FMVWX";
        case FCVTLS:
            return "FCVTLS";
        case FCVTLUS:
            return "FCVTLUS";
        case FCVTSL:
            return "FCVTSL";
        case FCVTSLU:
            return "FCVTSLU";
        case FLD:
            return "FLD";
        case FSD:
            return "FSD";
        case FMADDD:
            return "FMADDD";
        case FMSUBD:
            return "FMSUBD";
        case FNMSUBD:
            return "FNMSUBD";
        case FNMADDD:
            return "FNMADDD";
        case FADDD:
            return "FADDD";
        case FSUBD:
            return "FSUBD";
        case FMULD:
            return "FMULD";
        case FDIVD:
            return "FDIVD";
        case FSQRTD:
            return "FSQRTD";
        case FSGNJD:
            return "FSGNJD";
        case FSGNJND:
            return "FSGNJND";
        case FSGNJXD:
            return "FSGNJXD";
        case FMIND:
            return "FMIND";
        case FMAXD:
            return "FMAXD";
        case FCVTSD:
            return "FCVTSD";
        case FCVTDS:
            return "FCVTDS";
        case FEQD:
            return "FEQD";
        case FLTD:
            return "FLTD";
        case FLED:
            return "FLED";
        case FCLASSD:
            return "FCLASSD";
        case FCVTWD:
            return "FCVTWD";
        case FCVTWUD:
            return "FCVTWUD";
        case FCVTDW:
            return "FCVTDW";
        case FCVTDWU:
            return "FCVTDWU";
        case FCVTLD:
            return "FCVTLD";
        case FCVTLUD:
            return "FCVTLUD";
        case FMVXD:
            return "FMVXD";
        case FCVTDL:
            return "FCVTDL";
        case FCVTDLU:
            return "FCVTDLU";
        case FMVDX:
            return "FMVDX";
        default:
            return "UNKNOWN";
    }
}
